# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comments_comments_extratext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comments_text',
        ),
    ]
