# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 20:12
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20170307_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments_extraText',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='\u0412\u0430\u0448 \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439'),
        ),
    ]
