# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extUser', '0002_auto_20170129_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='extuser',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
