# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extUser', '0003_extuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/avatars/'),
        ),
    ]
