# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extUser', '0004_auto_20170204_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extuser',
            name='avatar',
            field=models.ImageField(blank=True, default='media/img/avatars/crip.png', null=True, upload_to='media/img/avatars/'),
        ),
    ]
